name: smartchef
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^5.6.7
  firebase_storage: ^12.4.5
  provider: ^6.0.5
  cupertino_icons: ^1.0.5
  cached_network_image: ^3.2.3
  timeago: ^3.5.0
  flutter_markdown: ^0.7.7
  shimmer: ^3.0.0
  image_picker: ^1.0.2
  uuid: ^4.5.1
  path: ^1.8.3
  http: ^1.1.0
  intl: ^0.19.0
  url_launcher: ^6.1.12
  share_plus: ^11.0.0
  mockito: ^5.4.2
  firebase_auth: ^5.5.3
  firebase_core: ^3.13.0
  flutter_dotenv: ^5.1.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  
  assets:
    - .env
